server:
  servlet:
    context-path: /springboot-1
  port: 8080
spring:
      datasource:
        url: jdbc:mysql://localhost:3306/db_springboot-1?useSSL=false
        username: root
        password: 15773272279wt..A
        driver-class-name: com.mysql.cj.jdbc.Driver
user:
          name: 万涛
          id: ${random.int} #产生随机数
          age: 20
